# 数据库信息
HOSTNAME = 'localhost'
PORT = 3306
USERNAME = 'root'
PASSWORD = 'Kaiserist2'
DATABASE = 'my_db_01'
DB_URI = f"mysql+pymysql://{USERNAME}:{PASSWORD}@{HOSTNAME}:{PORT}/{DATABASE}?charset=utf8mb4"
SQLALCHEMY_DATABASE_URI = DB_URI

SECRET_KEY = "KSOA;DKSAOP,;PSA"